spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.201:3306/eas_test?autoReconnect=true&useSSL=false
    username: root
    password: 4130
    type: com.alibaba.druid.pool.DruidDataSource

